package com.example.videri.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable

val LightColorScheme = lightColorScheme(
    primary = LightColors.Primary,
    onPrimary = LightColors.OnPrimary,
    primaryContainer = LightColors.PrimaryVariant,
    onPrimaryContainer = LightColors.OnPrimary,
    secondary = LightColors.Secondary,
    onSecondary = LightColors.OnSecondary,
    secondaryContainer = LightColors.SecondaryVariant,
    onSecondaryContainer = LightColors.OnSecondary,
    tertiary = ContentColors.Rating,
    onTertiary = LightColors.OnPrimary,
    tertiaryContainer = ContentColors.RatingBackground,
    onTertiaryContainer = LightColors.OnBackground,
    error = LightColors.Error,
    onError = LightColors.OnError,
    errorContainer = LightColors.Error,
    onErrorContainer = LightColors.OnError,
    background = LightColors.Background,
    onBackground = LightColors.OnBackground,
    surface = LightColors.Surface,
    onSurface = LightColors.OnSurface,
    surfaceVariant = LightColors.SurfaceVariant,
    onSurfaceVariant = LightColors.OnSurfaceVariant,
    outline = LightColors.Outline,
    outlineVariant = LightColors.OutlineVariant,
    scrim = LightColors.Scrim,
    inverseSurface = DarkColors.Surface,
    inverseOnSurface = DarkColors.OnSurface,
    inversePrimary = DarkColors.Primary,
    surfaceDim = LightColors.SurfaceVariant,
    surfaceBright = LightColors.Surface,
    surfaceContainerLowest = LightColors.Surface,
    surfaceContainerLow = LightColors.SurfaceVariant,
    surfaceContainer = LightColors.SurfaceVariant,
    surfaceContainerHigh = LightColors.SurfaceVariant,
    surfaceContainerHighest = LightColors.SurfaceVariant
)

val DarkColorScheme = darkColorScheme(
    primary = DarkColors.Primary,
    onPrimary = DarkColors.OnPrimary,
    primaryContainer = DarkColors.PrimaryVariant,
    onPrimaryContainer = DarkColors.OnPrimary,
    secondary = DarkColors.Secondary,
    onSecondary = DarkColors.OnSecondary,
    secondaryContainer = DarkColors.SecondaryVariant,
    onSecondaryContainer = DarkColors.OnSecondary,
    tertiary = ContentColors.Rating,
    onTertiary = DarkColors.OnPrimary,
    tertiaryContainer = ContentColors.RatingBackground,
    onTertiaryContainer = DarkColors.OnBackground,
    error = DarkColors.Error,
    onError = DarkColors.OnError,
    errorContainer = DarkColors.Error,
    onErrorContainer = DarkColors.OnError,
    background = DarkColors.Background,
    onBackground = DarkColors.OnBackground,
    surface = DarkColors.Surface,
    onSurface = DarkColors.OnSurface,
    surfaceVariant = DarkColors.SurfaceVariant,
    onSurfaceVariant = DarkColors.OnSurfaceVariant,
    outline = DarkColors.Outline,
    outlineVariant = DarkColors.OutlineVariant,
    scrim = DarkColors.Scrim,
    inverseSurface = LightColors.Surface,
    inverseOnSurface = LightColors.OnSurface,
    inversePrimary = LightColors.Primary,
    surfaceDim = DarkColors.SurfaceVariant,
    surfaceBright = DarkColors.Surface,
    surfaceContainerLowest = DarkColors.Surface,
    surfaceContainerLow = DarkColors.SurfaceVariant,
    surfaceContainer = DarkColors.SurfaceVariant,
    surfaceContainerHigh = DarkColors.SurfaceVariant,
    surfaceContainerHighest = DarkColors.SurfaceVariant
)
